# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.IntegerField()),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('employee_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personnel.Personnel')),
                ('grade', models.CharField(max_length=1)),
                ('years_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('employee_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personnel.Personnel')),
                ('specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('employee_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personnel.Personnel')),
                ('specialty', models.CharField(max_length=50)),
                ('contract_type', models.CharField(max_length=20)),
            ],
        ),
    ]
