# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('years_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('ssn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=20)),
                ('employee_no', models.ForeignKey(db_column='employee_no', on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=20)),
                ('contract_type', models.CharField(max_length=20)),
                ('contract_length', models.DateField()),
                ('surgery_type_no', models.IntegerField()),
                ('employee_no', models.ForeignKey(db_column='employee_no', on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='employee_no',
            field=models.ForeignKey(db_column='employee_no', on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel'),
        ),
    ]
