# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block1', models.BooleanField()),
                ('block2', models.BooleanField()),
                ('block3', models.BooleanField()),
                ('block4', models.BooleanField()),
                ('block5', models.BooleanField()),
                ('block6', models.BooleanField()),
                ('block7', models.BooleanField()),
                ('block8', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('working_ind', models.BooleanField()),
                ('employee_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Personnel')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Shift'),
        ),
    ]
