# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20171213_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set([('date', 'employee_no')]),
        ),
    ]
