# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20171213_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('attending', models.BooleanField()),
                ('shift_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Shift')),
            ],
        ),
    ]
