# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20171207_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='employee_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personnel.Personnel'),
        ),
    ]
