# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20171207_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
