# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_auto_20171207_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='specialty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='specialty',
            field=models.CharField(max_length=50),
        ),
    ]
