# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20171208_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgeon',
            name='surgery_type_no',
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='contract_length',
            field=models.DateField(blank=True, null=True, verbose_name='contract_length'),
        ),
    ]
